--- #YAML:1.0
name: Alien
version: 0.9
license: perl
distribution_type: module
requires: {}
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Alien:
    file: lib/Alien.pm
    version: 0.9
generated_by: Module::Build version 0.20
